# Generated by Django 4.2.7 on 2023-11-23 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchid', models.AutoField(primary_key=True, serialize=False)),
                ('branchname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address_longitude', models.CharField(max_length=50)),
                ('address_latitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageid', models.AutoField(primary_key=True, serialize=False)),
                ('image_created', models.DateTimeField()),
                ('image_uploaded', models.DateTimeField()),
                ('harvesterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Harvester', 'Harvester')], default='Harvester', max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palmapp.branch')),
            ],
        ),
        migrations.CreateModel(
            name='PalmDetail',
            fields=[
                ('palmid', models.AutoField(primary_key=True, serialize=False)),
                ('quality', models.CharField(max_length=50)),
                ('real', models.CharField(max_length=50)),
                ('predicted', models.BooleanField()),
                ('x1_coordinate', models.CharField(max_length=50)),
                ('y1_coordinate', models.CharField(max_length=50)),
                ('x2_coordinate', models.CharField(max_length=50)),
                ('y2_coordinate', models.CharField(max_length=50)),
                ('palm_image_uploaded', models.DateTimeField()),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palmapp.image')),
            ],
        ),
    ]
