# Generated by Django 4.2.7 on 2023-11-22 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palmapp', '0003_remove_user_mainid_remove_user_userid_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='harvester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
