# Generated by Django 4.2.7 on 2023-11-22 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palmapp', '0004_alter_image_harvester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='harvester',
        ),
        migrations.AddField(
            model_name='image',
            name='harvesterid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='palmapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='imageid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
