# Generated by Django 4.2.7 on 2023-11-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palmapp', '0006_alter_image_harvesterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Harvester', 'Harvester')], default='Harvester', max_length=20),
        ),
    ]
